"""Add settlement history and transaction types

Revision ID: a4cc88fc7669
Revises: 
Create Date: 2026-01-28 22:31:13.867134

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a4cc88fc7669'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settlement_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historical_settlements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('settlement_session_id', sa.Integer(), nullable=False),
    sa.Column('from_user_id', sa.Integer(), nullable=False),
    sa.Column('to_user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['settlement_session_id'], ['settlement_sessions.id'], ),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('settlements')
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('settlement_session_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'settlement_sessions', ['settlement_session_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('settlement_session_id')
        batch_op.drop_column('type')

    op.create_table('settlements',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('from_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('to_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('is_paid', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], name=op.f('settlements_from_user_id_fkey')),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], name=op.f('settlements_to_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('settlements_pkey'))
    )
    op.drop_table('historical_settlements')
    op.drop_table('settlement_sessions')
    # ### end Alembic commands ###
